### ISSUE TITLE
Legibilidade do código e sugestões de melhoria!

### ISSUE THREAD

**Issue by clcosta** [DevLucasLourenco/AllWhatsPy#27]
# *Escrita do código e sugestões de melhoria*
**Está muito difícil ler o seu código!** 

Entenda, não é uma critica ao seu projeto que é uma ideia sensacional. É uma critica a como ele foi escrito.

O Python assim como várias outras linguagens tem algumas convenções para se seguir, a convenção que engloba os padrões de um projeto Python é a [PEP-8](https://peps.python.org/pep-0008/). Existe na comunidade de desenvolvedores vários padrões que podem ser abordados que ajudam bastante independente do projeto e linguagem, um muito famoso que praticamente todo desenvolvedor tenta seguir é o `clean code` que você poderia pegar algumas ideias e aplicar neste projeto.

Muitas das convenções do Python foram seguidas neste projeto. Como Padrão de nome para funções (Snake Case) e funções bem descritivas e com comentários pertinentes na maioria.

Porém, existem algumas alterações para tornar o seu código bem mais legível sendo a mais gritante delas a **separação das funcionalidades em arquivos diferentes**. 

## Sugestões

Instale um formatador de código como o PEP-8, Black, Blue ou algum outro de sua preferência.

Depois adote um padrão de segregação de funcionalidades. Sem entrar muito afundo em padrões como o SOLID e DDD. Inicialmente, apenas selecione algumas funções que fazem sentido estarem  juntas e coloque-as em um modulo separado, pode parecer trabalhoso mas ninguém gosta de ficar procurando funcionalidade em um arquivo desnecessariamente gigante.

### _Sugestões com exemplos no código_

- [Exemplo 01](https://github.com/DevLucasLourenco/AllWhatsPy/blob/main/AllWhatsPy/AllWhatsPy.py#L180)

Constantemente tem código repetido dentro do seu arquivo, além de ter uma indentação meio difícil de acompanhar em alguns casos.

```py
def descer_conversa_origem_atual(quantidade: int = 1):

    '''
    Por padrão, não é necessário acrescentar nenhuma valor na quantidade, pois ele ja irá descer uma conversa por vez.
    '''

    # Sequência de comandos para fazer com que a conversa desça
    for i in range(quantidade):
        ActionChains(drive).key_down(Keys.CONTROL
                                        ).key_down(Keys.SHIFT
                                                    ).key_down(Keys.ALT
                                                            ).send_keys("]"
                                                                        ).perform()

    t.sleep(1)
    

    logging.info('descer_conversa_origem_atual() Terminou de Rodar!')


def subir_conversa_origem_atual(quantidade: int = 1):

    '''
    Por padrão, não é necessário acrescentar nenhuma valor na quantidade, pois ele ja irá subir uma conversa por vez.
    '''
    
    #Sequência  de comandos responsável por estar subindo a conversa atual
    for i in range(quantidade):
        ActionChains(drive).key_down(Keys.CONTROL
                                        ).key_down(Keys.SHIFT
                                                    ).key_down(Keys.ALT
                                                            ).send_keys("["
                                                                        ).perform()

    t.sleep(1)
    

    logging.info('subir_conversa_origem_atual() Terminou de Rodar!')

```

Estas funções poderiam ser:

```py
def _executa_ordem_de_teclas(tecla_especial: str = "[", quantidade: int = 1):
    # Esta função é executada diferentes vezes no código porem seguindo a mesma estrutura
    # você pode evitar repetição criando ela generica e reutilizando posteriormente
    for i in range(quantidade):
        ActionChains(drive).key_down(Keys.CONTROL).key_down(Keys.SHIFT).key_down(
            Keys.ALT
        ).send_keys(tecla_especial).perform()
    t.sleep(1)


def descer_conversa_origem_atual(quantidade: int = 1):
    """
    Por padrão, não é necessário acrescentar nenhuma valor na quantidade, pois ele ja irá descer uma conversa por vez.
    """
    _executa_ordem_de_teclas(tecla_especial="[", quantidade=quantidade)
    logging.debug("descer_conversa_origem_atual() Terminou de Rodar!")


def subir_conversa_origem_atual(quantidade: int = 1):
    """
    Por padrão, não é necessário acrescentar nenhuma valor na quantidade, pois ele ja irá subir uma conversa por vez.
    """
    _executa_ordem_de_teclas(tecla_especial="]", quantidade=quantidade)
    logging.debug("subir_conversa_origem_atual() Terminou de Rodar!")

```

Perceba que o seu código ainda mantem a mesma funcionalidade. Apenas com estas mudanças ele fica mais "clean", a leitura em si fica mais fácil. Ainda são funções que cumprem o mesmo objetivo, tendo em comum uma outra função genérica, sendo assim este conjunto poderia se tornar parte de um outro arquivo Python chamado `utils.py`, `chat_utils.py` ou até mesmo `funcoes_de_chat.py`.

- [Exemplo 02](https://github.com/DevLucasLourenco/AllWhatsPy#trabalhando-com-chatscontatosusuários)

Utilizar só funções tem seus bônus e ônus. Olhe este exemplo:

```py

import AllWhatsPy as awp

awp.conexao()
...
awp.desconetar()

```

Este código é a base de todo o seu projeto, porém imagine se eu simplesmente fazer assim:

```py

import AllWhatsPy as awp

awp.enviar_mensagem('Ops! Esqueci de me conectar antes!')

awp.desconetar()

```

**Ele vai quebrar logo na primeira função e você não sabe lidar com isto.**

Utilizando a função [`enviar_mensagem()`](https://github.com/DevLucasLourenco/AllWhatsPy/blob/main/AllWhatsPy/AllWhatsPy.py#L338) antes de realizar a conexão, é algo teoricamente "permitido" de se fazer apesar de nitidamente quebrar o código.

Por serem só funções não existe uma "conversa" entre elas, então o seu usuário pode chamar qualquer função a qualquer momento, mesmo que não faça sentido. Uma solução é definir uma flag global `conectado` e validar ela em toda função e por ai vai... mas perceba que seria muito mais pertinente ter isto disponível dentro de uma **classe AllWhatsPy**, exemplo:

```py
class AllWhatsPy:

	conectado = False

	def __init__(self):
		self.conexao()
		self.conectado = True

	def enviar_mensagem(self, msg: str):
		if not self.conectado:
			raise ConnectionError("AllWhatsPy não está conectado")
		...
```

Só de fazer está alteração já teríamos alguma "segurança" em relação a conexão, antes de enviar a mensagem ela poderia ser validada além de só poder ser chamada por uma instância da classe. Desta forma evita-se que o código quebre em uma parte que não deveria por um erro bobo do usuário já que não é mais permitido enviar mensagem sem estar conectado.

E ao utilizar classes você tem coisas incríveis como a implementação de `conexao()` e `desconectar()` dentro de um gerenciador `with` por exemplo:

```py
class AllWhatsPy:

    conectado = False

    def __enter__(self):
        self.conectado()
        self.conectado = True
        return self

    def __exit__(self, *args):
        self.desconetar()
        self.conectado = False

    def enviar_mensagem(self, msg: str = "Mensagem"):
        if not self.conectado:
            raise ConnectionError("AllWhatsPy não está conectado")
        print(msg)

    def conectado(self):
        ...

    def desconetar(self):
        ...


## Implementação ficaria assim:
with AllWhatsPy() as awp:
    print(awp.conectado)
    awp.enviar_mensagem("Gerenciador With Implementado!")

print(awp.conectado)
```

**Comment by DevLucasLourenco** [comment]
<div align="center">
<h1>
Olá, Claudio!
</h1>
<h3>
Primeramente, MUITO obrigado por esta issue. 
</h3>
</div>
</br>

Conforme você mesmo disse, a implementação de classes é muito importante e já era um grandiosíssimo objetivo meu. Entretanto, comecei a estudar python há relativamente pouco tempo, 7 meses , e também é a minha primeira linguagem de programação. Tem algumas coisas que eu ainda não entendo e essa é uma delas. Ainda não aprendi muito sobre POO, só utilizei `defs` para realizar o que eu queria até então. Estou para pegar `classes` para começar a estudar ainda, entretanto, como é um projeto que eu queria muito fazer, afinal eu estou usando no meu trabalho também, já lancei o mesmo da maneira que está agora. Sigo em constante estudo e adaptação do código.



- eu particularmente gostei muito do seu <b> exemplo 1</b>. Não havia pensado nessa maneira ainda. Por mais que tenha feito algo similar à outras partes do código, como a parte de botões de envio de attach, eu não pensei muito e você encontrou essa solução para mim.
estarei utilizando esta dica com toda certeza.

- estarei dando início à realização e separação dos arquivos como dito, gostei bastante também. Entretanto, nunca ouvi falar desse conceito de PEP-8. Com toda certeza pesquisarei.

Mais uma vez, agradeço a gentileza em disponibilizar seu tempo para a melhoria deste código. Todas as dicas e alertas foram apreciados e serão usados.

Att.
Lucas Lourenço
