### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by santana1509** [DevLucasLourenco/AllWhatsPy#56]
é possivel coletar todas as novas mensgaens enviadas em um grupo?

**Comment by DevLucasLourenco** [comment]
# "é possivel coletar todas as novas mensgaens enviadas em um grupo?" 

Olá, @santana1509!
Ao que entendi, o que deseja seria adentrar a um grupo e buscar todas mensagens mais recentes, correto?

Por agora, na nova versão do AWP — Encontrado em "New Patch (Alpha)" — , ainda não disponibilizei a varredura de chats para retornar mensagens. Entretanto, em sua versão antiga há sim essa feature. 
Com o decorrer do tempo, irei refatorar para com que na nova versão haja também.

Acompanhe os novos patches que serão lançados futuramente.
